name: Generate Snake

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        with:
          github_user_name: mohamedtaqysalmi
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - run: |
          git config user.name "mohamedtaqysalmi"
          git config user.email "mohamedtaqysalmi@gmail.com"
          git add dist/
          git diff --staged --quiet || git commit -m "chore: update snake animation"
          git push
